# Generated by Django 5.1.1 on 2024-09-04 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['student_id'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
