# Generated by Django 5.1.1 on 2024-09-20 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='first_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_choice_students', to='placement.program'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='second_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_choice_students', to='placement.program'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='third_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_choice_students', to='placement.program'),
        ),
    ]
