# Generated by Django 5.1.1 on 2024-09-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_alter_choice_first_choice_alter_choice_second_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
