# Generated by Django 5.1.1 on 2024-09-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0003_choice_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
